language: node_js
node_js:
  - 'stable'

cache:
  directories:
    - 'node_modules'

env:
  global:
    - NODE_ENV=test

services:
  - postgresql

addons:
  postgresql: '10'

install:
  - npm install --no-color --no-progress
  - npm install -g sequelize-cli

before_script:
  - psql -c 'create database barefoot_test;' -U postgres

script:
  - npm test

after_success:
  - npm run coverage
  - npm run coveralls