FROM node:alpine


#copy package.json to working dir to prevent reinstallation
#of npm packages 
COPY ./package.json /package.json

#run package installations
RUN npm install ./

#set working directory
WORKDIR '/var/www/app'


#copy the project into the working dir
COPY . .

#start your node project with this command
CMD ["npm","run","start"]