swagger: '2.0'
info:
  description: A simple international travel request API
  version: 1.0.0
  title:  Barefoot Nomad API
schemes:
 - https
# host: barefootNomad.com
# basePath: /v1
securityDefinitions:
  UserSecurity:
    type: basic
security:
  - UserSecurity: []
paths:
  /auth/signup:
    post:
      description: Users can sign up
      responses:
        200:
          description: User successfully signed up
          schema:
            type: object
            required:
              - first_name 
              - last_name
              - email
              - password
            properties:
              status:
                type: string
              data:
                type: object
                properties:
                  user_id: 
                    type: integer
                  token:
                    type: string
                    
        400:
          description: Invalid request
          schema:
            type: object
            properties:
              status:
                type: string
              error:
                type: string


/**
   * @swagger
   * components:
   *  schemas:
   *    User:
   *      properties:
   *        first_name:
   *          type: string
   *        last_name:
   *          type: string
   *        address:
   *          type: string
   *        preferred_lang:
   *         type: string
   *        preferred_currency:
   *          type: string
   *        gender:
   *          type: string
   */

  /**
   * @swagger
   * /api/v1/profile:
   *   put:
   *     tags:
   *       - Users
   *     description: Update user profile
   *     produces:
   *       - application/json
   *     requestBody:
   *      description: User data object
   *      required: true
   *      content:
   *       application/json:
   *          schema:
   *            $ref: '#/components/schemas/User'
   *     responses:
   *       200:
   *         description: Profile updated successfully
   *       500:
   *         description: Internal Server error
   */