// This function handles messages
export default {
  defaultWelcome: [
    'Welcome to Barefoot Nomad server.',
    'use /api/v1 as the base path url for the APIs of this app.',
  ],
  accommodationNotFound: 'The accommodation facility does not exist.',
  commentNotFound: 'The comment does not exist.',
  dateForFuture:
    'Please enter a date greater than the departure date for return date.',
  dateForToday:
    "Please your departure date must be equal to or greater than today's date.",
  deleteComment: 'Comment successfully deleted.',
  diffDepartment: 'You are not in the same department as the Travel Requester.',
  emptyAccommodation: 'You must select an accommodation.',
  emptyComment: 'comment cannot be empty.',
  emptyDepartureDate: 'You must state your departure date',
  emptyDestination: 'You must state your destination',
  emptyEmail: 'Email cannot be empty.',
  emptyFeedback: 'Feedback field cannot be empty.',
  emptyFirstname: 'First name cannot be empty.',
  emptyLastname: 'Last name cannot be empty.',
  emptyOrigin: 'You must state your current city.',
  emptyReturnDate: 'You must state your return date',
  emptyTravelPurpose: 'You must state your travel purpose',
  emptyTravelType: 'Sorry, travel type can not be empty.',
  getFeedback: (accommodationName) => `You have successfully retrieved feedback on our accommodation facility with name, ${accommodationName}.`,
  incorrectPassword: 'Sorry, the password entered is not correct.',
  invalidAccommodationId: 'The Accommodation ID must be an integer value.',
  invalidEmail: 'Please, enter a valid email address.',
  invalidToken: 'Invalid Token, please login.',
  invalidTravelType: 'Sorry you can only make return trip request here.',
  invalidTravelId: 'The travel ID must be an integer value.',
  invalidUserId:
    'Sorry you can only create the request with the id of the logged in user.',
  isNotInteger: 'You must enter a valid integer type.',
  isNotISODate: "Your date must be of ISO8601 standard '2019-01-10'.",
  lettersAlone: 'Only letters are allowed',
  loginSuccess: 'You have been logged in sucessfully.',
  logoutSuccess: 'Logged out successfully.',
  managerApproval: (pendingReq) => `You have ${pendingReq} requests requiring your approval`,
  managerNotFound: "Manager's detail missing",
  newFeedback: (accommodationName) => `You have successfully dropped a feedback on our accomodation facility with name, ${accommodationName}.`,
  noDigitInPassword: 'Password must contain at least one digit.',
  noEmail: 'Email cannot be empty.',
  nonExistentTravel: 'The travel request does not exist.',
  oneWayTripCreated: 'Your request has been successfully created',
  requestNotPending: 'This Travel Request is not Pending.',
  returnTripCreated: 'Your return trip request was created successfully.',
  requestNotOpen: 'Your request is no longer open for editing.',
  requestUpdated: 'Your request has been successfully updated',
  shortPassword: 'The length of the password must be 8 and above.',
  successComment: [
    'You have successfully commented on a travel request.',
    'You have successfully retrieved all comments for this travel request.',
  ],
  travelNotFound: 'The travel request does not exist.',
  unauthorized: 'Not authorized.',
  unauthorizedAccessToTravel:
    'Access denied. Accessible only by travel requester or his/her line manager.',
  unauthorizedCommentDelete: "comment can only be deleted by it's author",
  userApproval: 'Here are your request status',
  signupSuccess: (email) => `You have successfully registered with this email, ${email}.`,
  successfullyApproval: (requester) => `You have successfully approved a travel request from ${requester}.`,
  usedEmail: (email) => `User with this email (${email}) already exist.`,
  userEmailNotFound: (email) => `Sorry, there is no user with email ${email} in the database.`,
  userIdNotFound: (id) => `Sorry, there is no user with id: ${id} in the database.`,
  unregisteredEmail: (email) => `User with this email (${email}) not found in our database.`,
  updateRememberMe: 'You successfully updated your remember me record.',
  welcome: 'Welcome to Archangel Barefoot Nomad Web App API.',
  wrongRole: (role) => `Sorry, you are not a/an ${role}.`,

  getANotification: 'You have successfully retrieved a notification.',
  getAllNotification: 'You have successfully retrieved all your notification.',
  notificationNotFound: 'Notification not found.',
  invalidNotificationId: 'The notification ID must be a string.',
  notificationMessage: (date, origin) => `Your travel request created on ${date} with ${origin} as your origin has been approved.`
};
